### ISSUE TITLE
커뮤니티 Article 전체 불러오기 오류

### ISSUE THREAD

**Issue by wonkyoungChoi** [arsgsg1/Mediate#10]
### 📑 작업 사항
커뮤니티 Article 전체 불러오기 API 클라이언트 적용

### 📋 이슈 혹은 고려할 점
parameter 값으로 page, size에 각각 0, 5의 기본값을 넣고 불러오니 500 Error 발생

**Comment by arsgsg1** [comment]
url에 더블 슬래쉬 (//)가 들어가 오류가 난 걸로 확인했습니다. 해당 오류 수정하여 커밋했습니다~!
